name: Matrix with Node.js

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: [self-hosted]

    strategy:
      fail-fast: false
      max-parallel: 3

      matrix:
        version: [14, 16, 17]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.version }}

    - name: Run npm install on platform = ${{ matrix.platform }} node = ${{ matrix.version }}
      run: cd matrix-strategy/nodejs && npm install

    - name: Testing on platform = ${{ matrix.platform }} node = ${{ matrix.version }}
      run: cd matrix-strategy/nodejs && npm test
